# Generated by Django 5.0.4 on 2024-04-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年度')),
                ('revenue', models.FloatField(verbose_name='歳入額')),
                ('expenditure', models.FloatField(verbose_name='歳出額')),
            ],
        ),
    ]
